LD_FILE = boards/samd21x18-bootloader.ld
USB_VID = 0x1d50
USB_PID = 0x6067
USB_PRODUCT = "Orbotron 9001"
USB_MANUFACTURER = "Thingotron Labs"
USB_DEVICES = "CDC,MSC,HID"
USB_HID_DEVICES = "KEYBOARD,MOUSE,ORBOTRON"
CHIP_VARIANT = SAMD21E18A
CHIP_FAMILY = samd21

INTERNAL_FLASH_FILESYSTEM = 1
LONGINT_IMPL = NONE
CIRCUITPY_SMALL_BUILD = 1

SUPEROPT_GC = 0
